id: P004199
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:00:23.955583
source_metadata:
  id: bdr:W27877
  title: ཡང་ཏིག་ཡེ་ཤེས་མཐོང་གྲོལ་གྱི་ཆོས་སྐོར
  author: ''
  volumes:
    eb8c213536734f8abd7e81097b828f0d:
      image_group_id: I4483
      title: ''
      volume_number: 1
      total_pages: 602
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
