id: IC900C0A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:44:12+00:00'
last_modified: '2022-06-07T21:00:27.887566+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27877
  title: ཡང་ཏིག་ཡེ་ཤེས་མཐོང་གྲོལ་གྱི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    38C4:
      image_group_id: I4483
      title: ''
      total_pages: 602
      order: 1
      base_file: 38C4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
